export default {
    GET_THUMBNAILS_PAGE: {
        GETTINGS: "GET_THUMBNAILS_PAGE.GETTINGS",
        SUCCESS: "GET_THUMBNAILS_PAGE.SUCCESS",
        FAILURE: "GET_THUMBNAILS_PAGE.FAILURE"
    },
    GET_FULL_IMAGE: {
        GETTINGS: "GET_FULL_IMAGE.GETTINGS",
        SUCCESS: "GET_FULL_IMAGE.SUCCESS",
        FAILURE: "GET_FULL_IMAGE.FAILURE"
    },
    GET_SLIDE_IMAGE: {
        GETTINGS: "GET_SLIDE_IMAGE.GETTINGS",
        SUCCESS: "GET_SLIDE_IMAGE.SUCCESS",
        FAILURE: "GET_SLIDE_IMAGE.FAILURE"
    },
    REMOVE_FULL_IMAGE: "REMOVE_FULL_IMAGE",
    SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
    SET_SORT_BY: "SET_SORT_BY",
    SET_RANDOM_MODE: "SET_RANDOM_MODE"
}