export default {
    GET_THUMBNAILS_PAGE: {
        GETTINGS: "GET_THUMBNAILS_PAGE.GETTINGS",
        SUCCESS: "GET_THUMBNAILS_PAGE.SUCCESS",
        FAILURE: "GET_THUMBNAILS_PAGE.FAILURE"
    },
    GET_FULL_IMAGE: {
        GETTINGS: "GET_FULL_IMAGE.GETTINGS",
        SUCCESS: "GET_FULL_IMAGE.SUCCESS",
        FAILURE: "GET_FULL_IMAGE.FAILURE"
    },
    SET_SEARCH_TEXT: "SET_SEARCH_TEXT"
}